### ISSUE TITLE
Review: State of the field

### ISSUE THREAD

**Issue by thomaspinder** [jungtaekkim/bayeso#30]
I do not currently see a section in the paper that outlines the other BO packages i.e., the state of the field. As per JOSS' guidelines, could you please add such a section?

**Comment by jungtaekkim** [comment]
We added the state of the field in 743f1028d7a2d964491535f9afa04bfebcfd9513 and 8a5110489b7f1a93ff0aa1e3bc08c5db0365c430.  We have polished our paper more; please see the [revision](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05320/joss.05320/10.21105.joss.05320.pdf).
