### ISSUE TITLE
Supressing INFO on run_single_round

### ISSUE THREAD

**Issue by MarcosCarreira** [jungtaekkim/bayeso#36]
Thanks for the paper and package.
Is there a way to suppress the INFO printouts when running run_single_round?
Something like a verbose option?
Thanks

**Comment by jungtaekkim** [comment]
Hi @MarcosCarreira,

Thank you for your interest in our package.

Now, you can use the verbose option in https://github.com/jungtaekkim/bayeso/tree/0.6.1

You need to install BayesO 0.6.1 from source.

Please let me know if you have any further issues.

**Comment by MarcosCarreira** [comment]
Thanks!
